version: '3.2'

networks:
  network-grafana:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - network-grafana
    user: root
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: "true"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    expose:
      - 3000
    ports:
      - "3000:3000"

  reporter:
    user: root
    networks:
      - network-grafana
    image: joelvasiliev/reporter-grafana:dependencies-v2
    command: bash -c "rm /root/templates/Inmetrics-Layout.jpg && wget https://raw.githubusercontent.com/joel-vasiliev/grafana-files/main/Inmetrics-Layout.jpg -P /root/templates && rm /root/templates/template.tex && wget https://raw.githubusercontent.com/joel-vasiliev/grafana-files/main/template.tex -P /root/templates && grafana-reporter -ip grafana:3000 -templates=/root/templates"
    ports:
      - "8686:8686"
      
  renderer:
    networks:
      - network-grafana
    user: root
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
